 
# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  name: 'LinuxAgentPool'

steps:

- task: oc-cmd@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'Openshift-cluopf01'
    version: '4.9.13'
    cmd: 'oc status'
- task: Docker@2
  inputs:
    containerRegistry: 'Openshift-cluopf01-Image-Registry'
    repository: 'devops-testdemo3-tfs/imagestream-testdemo3-tfs'
    command: 'build'
    Dockerfile: '**/Dockerfile'
  displayName: 'Build docker file'